/* Original fixed-anchor artwork. renderAvatar is shared by previews, history and both
   exporters. Layer order: background -> rear hair -> ears -> face -> front hair ->
   eyes/blush -> facewear -> hair accessory. History stores validated options only. */
'use strict';
const TEXT = {
 zh:{title:'我的头像',edit:'装扮',hair:'发型',skin:'肤色',eyes:'眼睛',ears:'耳朵',accessory:'发饰',face:'面饰',background:'背景',generate:'生成头像',history:'生成历史',empty:'还没有生成的头像',clear:'清空历史',restore:'恢复编辑',remove:'删除',random:'随机搭配',reset:'重置',color:'颜色',hairColor:'发型颜色',skinColor:'肤色',eyeColor:'眼睛颜色',leftEye:'画面左侧眼睛',rightEye:'画面右侧眼睛',hetero:'异色瞳',side:'遮挡位置',left:'画面左侧',right:'画面右侧',custom:'自定义颜色',saved:'头像已保存到历史',duplicate:'这款头像已在历史中',restored:'已恢复，可以继续编辑',cleared:'历史已清空',storageError:'浏览器无法保存历史，请检查存储空间或隐私设置',corrupt:'部分历史数据无法读取，已保留原数据',downloadError:'下载失败，请重试',confirmClear:'确定清空全部生成历史？',cancel:'取消',confirm:'清空',download:'下载',size:'PNG 尺寸',footer:'gaze zako avatar · 头像工坊',hairNames:['短发','波波头','齐肩发','长直发','长卷发','单马尾','双马尾','双丸子头'],earNames:['无','猫耳','狐耳','兔耳','熊耳'],accessoryNames:['无','交叉发夹','星星发夹','蝴蝶结','双侧小蝴蝶结','花朵','女仆发箍','小皇冠'],faceNames:['无','圆框眼镜','椭圆框眼镜','方框眼镜','猫眼框眼镜','心形框眼镜','单眼眼罩'],backgroundNames:['黑色','白色','透明','蒂芙尼蓝 + 白点','粉色 + 白点','跨性别旗','粉色','蓝色']},
 en:{title:'Your avatar',edit:'Customize',hair:'Hair',skin:'Skin',eyes:'Eyes',ears:'Ears',accessory:'Accessories',face:'Facewear',background:'Background',generate:'Create avatar',history:'Your collection',empty:'No avatars yet',clear:'Clear history',restore:'Edit',remove:'Delete',random:'Randomize',reset:'Reset',color:'Color',hairColor:'Hair color',skinColor:'Skin tone',eyeColor:'Eye color',leftEye:'Screen-left eye',rightEye:'Screen-right eye',hetero:'Different eye colors',side:'Covered eye',left:'Screen left',right:'Screen right',custom:'Custom color',saved:'Avatar saved to your collection',duplicate:'This avatar is already in your collection',restored:'Avatar restored for editing',cleared:'History cleared',storageError:'Unable to save history. Check browser storage or privacy settings.',corrupt:'Some history could not be read. Original data was preserved.',downloadError:'Download failed. Please try again.',confirmClear:'Clear your entire avatar history?',cancel:'Cancel',confirm:'Clear',download:'Download',size:'PNG size',footer:'gaze zako avatar · Avatar Studio',hairNames:['Short','Bob','Shoulder length','Long straight','Long wavy','Ponytail','Twin tails','Double buns'],earNames:['None','Cat','Fox','Rabbit','Bear'],accessoryNames:['None','Crossed pins','Star clip','Bow','Twin bows','Flower','Maid headband','Crown'],faceNames:['None','Round glasses','Oval glasses','Square glasses','Cat-eye glasses','Heart glasses','Eyepatch'],backgroundNames:['Black','White','Transparent','Tiffany + dots','Pink + dots','Transgender flag','Pink','Blue']},
 ja:{title:'マイアバター',edit:'カスタマイズ',hair:'髪型',skin:'肌',eyes:'目',ears:'耳',accessory:'髪飾り',face:'顔アクセ',background:'背景',generate:'アバターを作成',history:'作成履歴',empty:'まだアバターがありません',clear:'履歴を全削除',restore:'編集',remove:'削除',random:'ランダム',reset:'リセット',color:'カラー',hairColor:'髪の色',skinColor:'肌の色',eyeColor:'目の色',leftEye:'画面左の目',rightEye:'画面右の目',hetero:'オッドアイ',side:'隠す目',left:'画面左',right:'画面右',custom:'カスタムカラー',saved:'履歴に保存しました',duplicate:'同じアバターが履歴にあります',restored:'編集を再開できます',cleared:'履歴を削除しました',storageError:'保存できません。ブラウザーの空き容量やプライバシー設定をご確認ください。',corrupt:'一部の履歴を読み込めませんでした。元のデータは保持されています。',downloadError:'ダウンロードに失敗しました。もう一度お試しください。',confirmClear:'すべての作成履歴を削除しますか？',cancel:'キャンセル',confirm:'削除',download:'ダウンロード',size:'PNG サイズ',footer:'gaze zako avatar · アバタースタジオ',hairNames:['ショート','ボブ','ミディアム','ロングストレート','ロングウェーブ','ポニーテール','ツインテール','お団子'],earNames:['なし','猫耳','狐耳','うさ耳','くま耳'],accessoryNames:['なし','クロスピン','星のピン','リボン','ツインリボン','お花','メイドカチューシャ','王冠'],faceNames:['なし','丸メガネ','楕円メガネ','四角メガネ','キャットアイ','ハートメガネ','眼帯'],backgroundNames:['黒','白','透明','ティファニー＋水玉','ピンク＋水玉','トランスジェンダーフラッグ','ピンク','ブルー']}
};
const DEFAULT={hair:2,hairColor:'#a9ceef',skinColor:'#fff0e8',eyeColor:'#242b3b',rightEye:'#6ca9c5',hetero:false,ears:0,accessory:0,accessoryColor:'#fff9fc',face:0,faceColor:'#635364',side:'left',background:0};
TEXT.zh.accessoryNames.push('冰晶蝴蝶结套饰','月亮玫瑰女仆套饰');
TEXT.zh.mouth='小嘴';TEXT.en.mouth='Small mouth';TEXT.ja.mouth='小さな口';
DEFAULT.mouth=false;
TEXT.en.accessoryNames.push('Crystal bow ensemble','Moon rose maid ensemble');
TEXT.ja.accessoryNames.push('氷晶リボンセット','月と薔薇のメイドセット');
TEXT.zh.accessoryNames.push('同侧双蝴蝶结','侧边丝带发夹','骨形发夹','蝴蝶结与波浪夹','交叠长发夹','荷叶发带与交叉夹');
TEXT.en.accessoryNames.push('Stacked bows','Side ribbon clips','Bone clip','Bows and wave clips','Crossed bar clips','Ruffled band and pins');
TEXT.ja.accessoryNames.push('重ねリボン','サイドリボンピン','ボーンピン','リボンと波形ピン','クロスバーピン','フリルバンドとピン');
const LIMITS={hair:8,ears:5,accessory:16,face:7,background:8};
const PRESETS={
 crystal:{hair:2,accessory:8,hairColor:'#acd2f2',accessoryColor:'#6998d5',eyeColor:'#23263e'},
 moon:{hair:2,accessory:9,hairColor:'#8886a5',accessoryColor:'#514975',eyeColor:'#23263e',mouth:true},
 white:{hair:5,accessory:15,hairColor:'#f5f3f2',accessoryColor:'#41404c',eyeColor:'#85b7cd'},
 lilac:{hair:6,ears:1,accessory:11,hairColor:'#d2bce6',accessoryColor:'#fafaff',eyeColor:'#9875bd'},
 dark:{hair:0,ears:1,accessory:4,hairColor:'#464352',accessoryColor:'#b84e59',eyeColor:'#dd815e'},
 glasses:{hair:0,accessory:10,face:1,hairColor:'#f0f1f4',accessoryColor:'#484656',faceColor:'#bdae9e',eyeColor:'#76a7c5'},
 pink:{hair:6,ears:4,accessory:12,hairColor:'#efb4ca',accessoryColor:'#fffaff',eyeColor:'#82afd0'},
 blue:{hair:0,accessory:10,hairColor:'#c2d2ed',accessoryColor:'#454453',eyeColor:'#7fb2d1'},
 purple:{hair:6,ears:1,accessory:13,hairColor:'#77688e',accessoryColor:'#ecc8e7',eyeColor:'#a487c9'},
 maid:{hair:3,accessory:6,hairColor:'#ecd6ac',accessoryColor:'#fffaf5',eyeColor:'#83b6d0'},
 rabbit:{hair:6,ears:3,accessory:4,hairColor:'#45414c',accessoryColor:'#d67883',eyeColor:'#d78565'},
 silver:{hair:0,accessory:14,hairColor:'#c3c1cb',accessoryColor:'#55545f',eyeColor:'#83b3d1'}
};
const PRESET_NAMES={zh:['冰晶','月亮女仆','白发发带','紫发猫耳','黑发猫耳','白发眼镜','粉发熊耳','蓝发双结','紫发波浪夹','金发女仆','黑发兔耳','银发长夹'],en:['Crystal','Moon maid','White band','Lilac cat','Dark cat','White glasses','Pink bear','Blue bows','Purple clips','Blonde maid','Dark rabbit','Silver clips'],ja:['氷晶','月メイド','白髪バンド','紫髪猫耳','黒髪猫耳','白髪メガネ','桃髪くま耳','青髪リボン','紫髪ピン','金髪メイド','黒髪うさ耳','銀髪ピン']};
const PALETTES={hairColor:['#f5f1ed','#e7dff0','#b6c9e4','#efbfd0','#efd7a0','#bb8d6b','#846172','#484250','#262732'],skinColor:['#fff0e5','#f8dfcb','#efc7aa','#d7a27f','#b67e5d','#885940','#593d32'],eyeColor:['#6ca9c5','#8b73ac','#75a18c','#d18163','#dba345','#a36383','#635364','#343844'],accessoryColor:['#fff9fc','#f0abc8','#a9cde5','#c3b5df','#f0d18c','#8cbcb2','#635364'],faceColor:['#635364','#c49a7c','#d393ad','#a6bdcc','#f3dfb3','#fff9fc','#25252c']};
const STORAGE='gaze-zako-avatar.history.v1';
let lang='en',state={...DEFAULT},tab='hair',size=1024,history=[],storageBlocked=false;
try{const saved=localStorage.getItem('gaze-zako-avatar.language');lang=TEXT[saved]?saved:((navigator.language||'en').startsWith('zh')?'zh':(navigator.language||'en').startsWith('ja')?'ja':'en');}catch{}
const t=k=>TEXT[lang][k];
const icon=(name)=>{const paths={download:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/>',reset:'<path d="M3 11a9 9 0 1 1 2.6 6.4M3 3v8h8"/>',random:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M7.5 7.5h.01M16.5 7.5h.01M12 12h.01M7.5 16.5h.01M16.5 16.5h.01"/>',trash:'<path d="M3 6h18M9 6V4h6v2M5 6l1 14h12l1-14M10 10v6M14 10v6"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`;};
function validConfig(raw){if(!raw||typeof raw!=='object')return null;const s={...DEFAULT};for(const [k,n]of Object.entries(LIMITS)){if(!Number.isInteger(raw[k])||raw[k]<0||raw[k]>=n)return null;s[k]=raw[k];}for(const k of ['hairColor','skinColor','eyeColor','rightEye','accessoryColor','faceColor']){if(!/^#[0-9a-f]{6}$/i.test(raw[k]))return null;s[k]=raw[k].toLowerCase();}s.hetero=raw.hetero===true;s.mouth=raw.mouth===true;s.side=raw.side==='right'?'right':'left';return s;}
function loadHistory(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'[]');if(!Array.isArray(raw))throw Error();history=raw.map(x=>{const config=validConfig(x.config);return config&&typeof x.id==='string'&&/^[a-z0-9-]+$/i.test(x.id)&&typeof x.at==='string'?{id:x.id,at:x.at,config}:null;}).filter(Boolean);if(history.length!==raw.length)throw Error();}catch{storageBlocked=true;setTimeout(()=>toast('corrupt'),100);}}
function persist(next){if(storageBlocked){toast('corrupt');return false;}try{localStorage.setItem(STORAGE,JSON.stringify(next));history=next;return true;}catch{toast('storageError');return false;}}
function tone(hex,amount){return '#'+hex.slice(1).match(/../g).map(x=>Math.max(0,Math.min(255,parseInt(x,16)+amount)).toString(16).padStart(2,'0')).join('');}
function path(d,fill,extra=''){return `<path d="${d}" fill="${fill}" ${extra}/>`;}
function ellipse(x,y,rx,ry,fill,extra=''){return `<ellipse cx="${x}" cy="${y}" rx="${rx}" ry="${ry}" fill="${fill}" ${extra}/>`;}
function background(s){const colors=['#202023','#ffffff','none','#81d8d0','#f4b5d0',null,'#f4bfd4','#b7d9ef'];if(s.background===5)return ['#5bcefa','#f5a9b8','#ffffff','#f5a9b8','#5bcefa'].map((c,i)=>`<rect y="${i*200}" width="1000" height="200" fill="${c}"/>`).join('');let out=`<rect width="1000" height="1000" fill="${colors[s.background]}"/>`;if([3,4].includes(s.background)){for(let y=45;y<1000;y+=112)for(let x=(Math.floor(y/112)%2?85:30);x<1000;x+=112)out+=ellipse(x,y,10,10,'#ffffff');}return out;}
function bow(x,y,c,scale=1){return `<g transform="translate(${x} ${y}) scale(${scale})">${path('M0 0Q-95-80-95-28Q-112 42-16 17L0 4Q85 67 91 22Q118-48 25-15Z',c)}${ellipse(0,2,18,22,tone(c,-18))}</g>`;}
function star(x,y,c){return `<g transform="translate(${x} ${y})">${path('M0-40 12-13 42-10 20 11 25 42 0 27-26 42-21 11-43-10-12-13Z',c)}</g>`;}
function renderAvatar(s){const h=s.hairColor,shadow=tone(h,-24),a=s.accessoryColor,f=s.faceColor;
 // Transform the entire character, never the background, so every sticker and export
 // shares the lower-left peek. Hair and ear tips may crop at the top. Saved options also
 // use this composition; history contains no raster snapshots or position overrides.
 const framing=s.ears===3?'translate(-145 25) scale(1.07) rotate(17 500 700)':s.ears===2?'translate(-225 -70) scale(1.27) rotate(17 500 700)':s.ears===1?'translate(-245 -170) scale(1.3) rotate(17 500 700)':s.accessory===7?'translate(-245 -240) scale(1.38) rotate(17 500 700)':'translate(-268 -276) scale(1.25) rotate(17 500 700)';
 let out=background(s)+`<g data-character="lower-left" transform="${framing}">`;
 // All silhouettes share a face anchor; alternate rear/front paths keep accessories aligned.
 const rear=[
 'M185 965Q96 703 208 480Q325 283 548 322Q836 338 834 677L904 917 778 881 785 1000H190Z',
 'M152 1000Q115 757 166 555Q230 319 490 315Q777 300 839 569Q888 795 839 1000Z',
 'M127 1000Q181 858 150 717Q119 440 364 337Q673 240 820 488Q875 647 821 805L916 1000Z',
 'M126 1000 150 655Q132 384 408 322Q766 252 854 585L900 1000Z',
 'M135 1000Q55 947 124 865Q46 776 132 682Q81 570 197 447Q319 270 560 319Q835 318 867 587Q944 684 876 761Q966 869 879 911Q947 982 874 1000Z',
 'M681 435Q794 296 916 401Q1015 567 902 740Q829 847 952 1000H767Q681 824 786 633L698 566M174 1000Q117 708 194 516Q292 300 540 320Q804 330 844 617L810 1000Z',
 'M243 537Q120 360 57 533Q-1 689 58 812L17 1000H194L266 662M742 530Q881 361 947 537Q1004 729 952 845L988 1000H820L727 656M154 1000 160 634Q168 334 477 313Q803 304 844 620L844 1000Z',
 'M230 466C-13 491 86 191 254 294Q365 310 314 460M743 464C1020 465 892 194 742 293Q640 319 692 459M149 1000 170 594Q196 307 506 316Q786 317 836 610L851 1000Z'];
out+=referenceAccessory(s,'rear');
out+=path(rear[s.hair],shadow);
if(s.ears===1||s.ears===2){const tall=s.ears===2;out+=path(`M194 581Q136 410 ${tall?'115 163':'139 276'}Q305 300 357 437Z`,h)+path(`M806 581Q864 410 ${tall?'885 163':'861 276'}Q695 300 643 437Z`,h);out+=path(`M207 505  ${tall?'157 225':'177 328'} 299 432Z`,'#e9a7b9')+path(`M793 505 ${tall?'843 225':'823 328'} 701 432Z`,'#e9a7b9');}
if(s.ears===3){out+=path('M260 463Q129 161 213 52Q297 16 339 415Z',h)+path('M650 419Q696 7 782 60Q877 137 742 468Z',h)+path('M266 380Q198 132 224 98Q259 84 296 376Z','#e9a7b9')+path('M694 381Q729 98 766 103Q805 137 738 382Z','#e9a7b9');}
if(s.ears===4){out+=ellipse(222,373,110,113,h)+ellipse(778,373,110,113,h)+ellipse(222,374, 60,65,'#e9a7b9')+ellipse(778,374,60,65,'#e9a7b9');}
// Enlarge cheeks independently of facial details; all previews and exports share this contour.
out+=ellipse(500,811,390,395,s.skinColor);
// Shorten locks around the crown to expose more forehead while retaining accessory anchors.
out+=`<g transform="translate(-30 33) scale(1.06 .90)">${illustratedHair(s.hair,h)}</g>`;
// Keep the original facewear anchors; lift the entire facial-detail group together.
out+='<g transform="translate(0 -68)">';
out+=ellipse(360,833,43,72,s.eyeColor)+ellipse(644,846,43,72,s.hetero?s.rightEye:s.eyeColor);
out+=ellipse(275,920,50,29,'#f7b9c2','opacity=".65"')+ellipse(683,938,44,29,'#f7b9c2','opacity=".65"');
if(s.mouth)out+='<path d="M462 928Q475 948 494 937Q508 929 522 940Q541 952 552 931" fill="none" stroke="#dba3a8" stroke-width="5" stroke-linecap="round"/>';
const frame='fill="none" stroke="'+f+'" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"';
if(s.face>0&&s.face<6){out+=`<g ${frame}>`;if(s.face===1)out+='<circle cx="357" cy="835" r="87"/><circle cx="646" cy="846" r="87"/>';if(s.face===2)out+='<ellipse cx="357" cy="835" rx="96" ry="71"/><ellipse cx="646" cy="846" rx="96" ry="71"/>';if(s.face===3)out+='<rect x="268" y="761" width="178" height="149" rx="25"/><rect x="557" y="772" width="178" height="149" rx="25"/>';if(s.face===4)out+='<path d="M256 751Q366 769 444 801Q449 924 350 918Q273 912 256 751ZM748 762Q638 780 560 812Q555 935 654 929Q731 923 748 762Z"/>';if(s.face===5)out+='<path d="M358 777C294 697 221 814 358 921C495 814 422 697 358 777ZM646 788C582 708 509 825 646 932C783 825 710 708 646 788Z"/>';out+='<path d="M446 827Q501 798 557 836M269 813 233 793M733 830 767 810"/></g>';}
if(s.face===6){const x=s.side==='left'?360:644,y=s.side==='left'?833:846;out+=`<path d="M240 731 772 917" stroke="${f}" stroke-width="15"/>`+path(`M${x-74} ${y-69}Q${x} ${y-87} ${x+74} ${y-69}L${x+69} ${y+30}Q${x} ${y+114} ${x-69} ${y+30}Z`,f);}
out+='</g>';
const ax=[300,288,285,284,287,295,265,293][s.hair];
if(s.accessory===1)out+=`<g stroke="${a}" stroke-width="17" stroke-linecap="round"><path d="M${ax-40} 566l81 51m-77 5 75-69"/></g>`;
if(s.accessory===2)out+=star(ax,575,a);
if(s.accessory===3)out+=bow(730,467,a,1.12);
if(s.accessory===4)out+=bow(ax-30,578,a,.64)+bow(1000-ax+30,581,a,.64);
if(s.accessory===5){for(let i=0;i<5;i++)out+=ellipse(ax+Math.cos(i*Math.PI*2/5)*29,562+Math.sin(i*Math.PI*2/5)*29,23,23,a);out+=ellipse(ax,562,17,17,'#eac975');}
if(s.accessory===6){out+=`<path d="M209 493C295 254 647 234 789 493" fill="none" stroke="${tone(a,-35)}" stroke-width="35"/>`;for(let i=0;i<9;i++){const angle=(-160+i*17.5)*Math.PI/180,x=499+299*Math.cos(angle),y=492+199*Math.sin(angle);out+=`<g transform="translate(${x} ${y}) rotate(${angle*180/Math.PI+90})">${path('M-32 9-39-53Q-35-69-14-65L18-65Q39-65 40-48L31 9Z',a)}${path('M22-63Q34-60 36-45L30 9H17Z',tone(a,-17))}</g>`;}out+=bow(218,483,shadow,.6)+bow(783,483,shadow,.6);}
if(s.accessory===7)out+=path('M405 324 382 224 447 262 495 185 547 262 614 224 589 324Z',a)+path('M409 306H586V331H409Z',tone(a,-22))+ellipse(495,273,12,15,'#e69eb8');
out+=referenceAccessory(s,'front');
return `<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000" viewBox="0 0 1000 1000" role="img" aria-label="gaze zako avatar">${out}</g></svg>`;
}
function swatches(key,label){const colors=PALETTES[key]||PALETTES.eyeColor;return `<div class="color-section"><label class="color-title" for="color-${key}">${label}</label><div class="swatches">${colors.map(c=>`<button class="swatch ${state[key]===c?'active':''}" style="--swatch:${c}" data-color-key="${key}" data-color="${c}" title="${label}: ${c}" aria-label="${label}: ${c}" aria-pressed="${state[key]===c}"></button>`).join('')}<input class="custom-color" id="color-${key}" type="color" value="${state[key]}" data-custom="${key}" title="${t('custom')}"><span class="color-hex">${state[key].toUpperCase()}</span></div></div>`;}
function renderPanel(){document.querySelector('#reference-presets').innerHTML=Object.entries(PRESETS).map(([key,config],i)=>`<button data-preset="${key}" title="${PRESET_NAMES[lang][i]}">${renderAvatar({...DEFAULT,...config})}<span>${PRESET_NAMES[lang][i]}</span></button>`).join('');const listKey=tab==='hair'?'hairNames':tab==='ears'?'earNames':tab==='accessory'?'accessoryNames':tab==='face'?'faceNames':'backgroundNames';let html=`<div class="panel-heading"><h2>${t(tab)}</h2>${LIMITS[tab]?`<span class="count">${String(LIMITS[tab]).padStart(2,'0')}</span>`:''}</div>`;
if(LIMITS[tab])html+=`<div class="tiles">${TEXT[lang][listKey].map((name,i)=>{let sample={...state,[tab]:i};if(tab==='hair')sample={...sample,accessory:0,ears:0,face:0};if(tab==='ears')sample.accessory=0;return `<button class="tile ${state[tab]===i?'active':''}" data-option="${i}" aria-pressed="${state[tab]===i}"><div class="tile-visual">${tab==='background'?`<svg viewBox="0 0 1000 1000" aria-hidden="true">${i===2?'<defs><pattern id="checker" width="200" height="200" patternUnits="userSpaceOnUse"><rect width="200" height="200" fill="white"/><path d="M0 0H100V100H0ZM100 100H200V200H100Z" fill="#e9e4e8"/></pattern></defs><rect width="1000" height="1000" fill="url(#checker)"/>':background(sample)}</svg>`:renderAvatar(sample)}</div><span class="tile-label">${name}</span></button>`;}).join('')}</div>`;
if(tab==='hair')html+=swatches('hairColor',t('hairColor'));
if(tab==='skin')html+=swatches('skinColor',t('skinColor'));
if(tab==='face')html+=`<label class="check-row"><input id="mouth" type="checkbox" ${state.mouth?'checked':''}>${t('mouth')}</label>`;
if(tab==='eyes'){html+=swatches('eyeColor',state.hetero?t('leftEye'):t('eyeColor'))+`<label class="check-row"><input id="hetero" type="checkbox" ${state.hetero?'checked':''}>${t('hetero')}</label>`;if(state.hetero)html+=swatches('rightEye',t('rightEye'));}
if(tab==='accessory'&&state.accessory)html+=swatches('accessoryColor',t('color'));
if(tab==='face'&&state.face){html+=swatches('faceColor',t('color'));if(state.face===6)html+=`<div class="color-section"><span class="color-title">${t('side')}</span><div class="segmented">${['left','right'].map(x=>`<button data-side="${x}" aria-pressed="${state.side===x}" class="${state.side===x?'active':''}">${t(x)}</button>`).join('')}</div></div>`;}
document.querySelector('#panel').innerHTML=html;}
function renderHistory(){document.querySelector('#history-count').textContent=history.length;document.querySelector('#clear').disabled=!history.length;document.querySelector('#history-content').innerHTML=history.length?`<div class="history-grid">${history.map(item=>`<article class="history-item"><button class="history-image" data-restore="${item.id}" title="${t('restore')}" aria-label="${t('restore')}">${renderAvatar(item.config)}</button><div class="history-actions"><button data-history-download="${item.id}" data-format="svg" aria-label="${t('download')} SVG">SVG</button><button data-history-download="${item.id}" data-format="png" aria-label="${t('download')} PNG">PNG</button><button class="icon-button" data-remove="${item.id}" title="${t('remove')}" aria-label="${t('remove')}">${icon('trash')}</button></div></article>`).join('')}</div>`:`<div class="empty">${t('empty')}</div>`;}
function render(){document.documentElement.lang={zh:'zh-CN',en:'en',ja:'ja'}[lang];document.title=`gaze zako avatar · ${t('title')}`;document.querySelector('#language').value=lang;document.querySelector('#app').innerHTML=`<div class="workspace"><section class="preview-column"><div class="section-heading"><div><p class="eyebrow">GAZE ZAKO / 01</p><h1>${t('title')}</h1></div><div class="preview-tools"><button class="icon-button" id="random" title="${t('random')}" aria-label="${t('random')}">${icon('random')}</button><button class="icon-button" id="reset" title="${t('reset')}" aria-label="${t('reset')}">${icon('reset')}</button></div></div><div class="preview" id="preview">${renderAvatar(state)}</div><button class="primary generate" id="generate">${icon('spark')}${t('generate')}</button><div class="download-row"><button data-download="svg" aria-label="${t('download')} SVG">${icon('download')}SVG</button><button data-download="png" aria-label="${t('download')} PNG">${icon('download')}PNG</button><select id="size" aria-label="${t('size')}">${[512,1024,2048].map(n=>`<option value="${n}" ${n===size?'selected':''}>${n} px</option>`).join('')}</select></div></section><section class="editor" aria-label="${t('edit')}"><nav class="tabs" aria-label="${t('edit')}">${['hair','skin','eyes','ears','accessory','face','background'].map(k=>`<button class="tab ${tab===k?'active':''}" data-tab="${k}" aria-pressed="${tab===k}">${t(k)}</button>`).join('')}</nav><div id="panel"></div></section></div><section class="history"><div class="history-heading"><h2>${t('history')}<span class="badge" id="history-count"></span></h2><button id="clear">${t('clear')}</button></div><div id="history-content"></div></section><footer>${t('footer')}</footer>`;renderPanel();renderHistory();document.querySelector('#confirm-title').textContent=t('confirmClear');document.querySelector('#cancel').textContent=t('cancel');document.querySelector('#confirm-action').textContent=t('confirm');}
function update(){document.querySelector('#preview').innerHTML=renderAvatar(state);renderPanel();}
let toastTimer;function toast(key){const el=document.querySelector('#toast');el.textContent=t(key);el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3500);}
function fingerprint(config){const s={...config};if(!s.hetero)s.rightEye=DEFAULT.rightEye;if(!s.accessory)s.accessoryColor=DEFAULT.accessoryColor;if(!s.face)s.faceColor=DEFAULT.faceColor;if(s.face!==6)s.side='left';return JSON.stringify(s);}
function save(){if(history.some(x=>fingerprint(x.config)===fingerprint(state))){toast('duplicate');return;}const entry={id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9),at:new Date().toISOString(),config:{...state}};if(persist([entry,...history])){renderHistory();toast('saved');}}
function triggerDownload(blob,extension){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gaze-zako-avatar-${Date.now()}.${extension}`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function download(config,format){try{const svg=renderAvatar(config);if(format==='svg'){triggerDownload(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),'svg');return;}const image=new Image(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});const canvas=document.createElement('canvas');canvas.width=canvas.height=size;canvas.getContext('2d').drawImage(image,0,0,size,size);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error();triggerDownload(blob,'png');}finally{URL.revokeObjectURL(url);}}catch{toast('downloadError');}}
document.querySelector('#language').addEventListener('change',e=>{lang=e.target.value;try{localStorage.setItem('gaze-zako-avatar.language',lang);}catch{}render();});
document.querySelector('#app').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.tab){tab=d.tab;render();document.querySelector(`[data-tab="${tab}"]`).focus({preventScroll:true});}else if(d.option!==undefined){state[tab]=Number(d.option);update();}else if(d.color){state[d.colorKey]=d.color;update();}else if(d.side){state.side=d.side;update();}else if(d.download){download({...state},d.download);}else if(d.restore){const item=history.find(x=>x.id===d.restore);if(item){state={...item.config};update();document.querySelector('.preview-column').scrollIntoView({behavior:'smooth',block:'start'});toast('restored');}}else if(d.remove){if(persist(history.filter(x=>x.id!==d.remove)))renderHistory();}else if(d.historyDownload){const item=history.find(x=>x.id===d.historyDownload);if(item)download(item.config,d.format);}else if(b.id==='generate')save();else if(b.id==='clear')document.querySelector('#confirm').showModal();else if(b.id==='reset'){state={...DEFAULT};update();}else if(b.id==='random'){for(const [key,count]of Object.entries(LIMITS))state[key]=Math.floor(Math.random()*count);for(const [key,colors]of Object.entries(PALETTES))state[key]=colors[Math.floor(Math.random()*colors.length)];state.rightEye=PALETTES.eyeColor[Math.floor(Math.random()*PALETTES.eyeColor.length)];update();}});
document.querySelector('#app').addEventListener('input',e=>{const key=e.target.dataset.custom;if(key){state[key]=e.target.value;document.querySelector('#preview').innerHTML=renderAvatar(state);e.target.nextElementSibling.textContent=e.target.value.toUpperCase();document.querySelectorAll(`[data-color-key="${key}"]`).forEach(b=>{b.classList.toggle('active',b.dataset.color===state[key]);b.setAttribute('aria-pressed',b.dataset.color===state[key]);});}});
document.querySelector('#app').addEventListener('change',e=>{if(['hetero','mouth'].includes(e.target.id)){state[e.target.id]=e.target.checked;update();}if(e.target.id==='size')size=Number(e.target.value);});
document.querySelector('#confirm').addEventListener('close',()=>{if(document.querySelector('#confirm').returnValue==='confirm'&&persist([])){renderHistory();toast('cleared');}});
document.querySelector('#reference-presets').addEventListener('click',e=>{const preset=e.target.closest('[data-preset]')?.dataset.preset;if(!PRESETS[preset])return;state={...DEFAULT,...PRESETS[preset]};update();});
loadHistory();render();
